version: "3.9"

services:
  namenode-1:
    container_name: namenode-1
    build:
      context: ./namenode-img
      dockerfile: dockerfile
    depends_on:
      - nfs-server
    tty: false
    ports:
      - "8020:8020"
      - "8021:8021"
    volumes:
      - ./namenode-data/nn1/etc:/etc/hadoop:rw
      - ./namenode-data/nn1/metadata:/metadata:rw
      - ./namenode-data/nn1/data:/data:rw
      - ./namenode-data/nn1/src:/root/src:rw
    networks:
      hadoop-server:
        ipv4_address: 128.0.0.2
    environment:
      - "TERM=xterm-256color"
  namenode-2:
    container_name: namenode-2
    build:
      context: ./namenode-img
      dockerfile: dockerfile
    depends_on:
      - nfs-server
    tty: false
    ports:
      - "8022:8020"
      - "8023:8021"
    volumes:
      - ./namenode-data/nn2/etc:/etc/hadoop:rw
      - ./namenode-data/nn2/metadata:/metadata:rw
      - ./namenode-data/nn2/data:/data:rw
      - ./namenode-data/nn2/src:/root/src:rw
    networks:
      hadoop-server:
        ipv4_address: 128.0.0.3

    environment:
      - "TERM=xterm-256color"
  nfs-server:
    build:
      context: ./docker-nfs-server
      dockerfile: dockerfile
    ports:
      - "2049:2049"
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    environment:
      - SHARED_DIRECTORY=/data/share
    volumes:
      - ./nfs_share/data:/data/share
    networks:
      hadoop-server:
        ipv4_address: 128.0.0.254

networks:
  hadoop-server:
    ipam:
      driver: default
      config:
        - subnet: "128.0.0.0/24"
