version: "3.9"

services:
  namenode-1:
    build:
      context: ./namenode_1
      dockerfile: dockerfile
    depends_on:
      - nfs-server
    ports:
      - "8020:8020"
      - "8021:8021"
    volumes:
      - ./namenode/namenode_1/etc:/etc/hadoop:rw
      - ./namenode/namenode_1/metadata:/metadata:rw
      - ./namenode/namenode_1/data:/data:rw
      - ./namenode/namenode_1/src:/root/src:rw
    networks:
      hadoop-server:
        ipv4_address: 128.0.0.2
    environment:
      - "TERM=xterm-256color"
  namenode-2:
    build:
      context: ./namenode_2
      dockerfile: dockerfile
    depends_on:
      - nfs-server
    ports:
      - "8022:8020"
      - "8023:8021"
    volumes:
      - ./namenode/namenode_2/etc:/etc/hadoop:rw
      - ./namenode/namenode_2/metadata:/metadata:rw
      - ./namenode/namenode_2/data:/data:rw
      - ./namenode/namenode_2/src:/root/src:rw
    networks:
      hadoop-server:
        ipv4_address: 128.0.0.3

    environment:
      - "TERM=xterm-256color"
  nfs-server:
    build:
      context: ./docker-nfs-server
      dockerfile: Dockerfile
    ports:
      - "2049:2049"
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    environment:
      - SHARED_DIRECTORY=/data/share
    volumes:
      - ./nfs_share/data:/data/share
    networks:
      hadoop-server:
        ipv4_address: 128.0.0.254

networks:
  hadoop-server:
    ipam:
      driver: default
      config:
        - subnet: "128.0.0.0/24"
