version: "3.9"

services:
  namenode-1:
    container_name: namenode-1
    build:
      context: ./namenode-img
      dockerfile: dockerfile
    depends_on:
      - nfs-server
    tty: false
    ports:
      - "8020:8020"
      - "8021:8021"
    volumes:
      - ./namenode-data/nn1/etc:/etc/hadoop:rw
      - ./namenode-data/nn1/metadata:/metadata:rw
      - ./namenode-data/nn1/data:/data:rw
      - ./namenode-data/nn1/src:/root/src:rw
    networks:
      hadoop-server:
        ipv4_address: 128.0.0.2
    environment:
      - "TERM=xterm-256color"
  namenode-2:
    container_name: namenode-2
    build:
      context: ./namenode-img
      dockerfile: dockerfile
    depends_on:
      - nfs-server
    tty: false
    volumes:
      - ./namenode-data/nn2/etc:/etc/hadoop:rw
      - ./namenode-data/nn2/metadata:/metadata:rw
      - ./namenode-data/nn2/data:/data:rw
      - ./namenode-data/nn2/src:/root/src:rw
    networks:
      hadoop-server:
        ipv4_address: 128.0.0.3

    environment:
      - "TERM=xterm-256color"
  namenode-3:
    container_name: namenode-3
    build:
      context: ./namenode-img
      dockerfile: dockerfile
    # depends_on:
    #   - nfs-server
    tty: false
    volumes:
      - ./namenode-data/nn3/etc:/etc/hadoop:rw
      - ./namenode-data/nn3/metadata:/metadata:rw
      - ./namenode-data/nn3/data:/data:rw
      - ./namenode-data/nn3/src:/root/src:rw
    networks:
      hadoop-server:
        ipv4_address: 128.0.0.4

    environment:
      - "TERM=xterm-256color"
  nfs-server:
    build:
      context: ./docker-nfs-server
      dockerfile: dockerfile
    ports:
      - "2045:2049"
    # cap_add:
    #   - CAP_SYS_ADMIN
    #   - CAP_SETPCAP
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data/share
      - SHARED_DIRECTORY_2=/data/backup_1  
    volumes:
      - ./nfs_share/data:/data/share
      - ./nfs_share/backup_1:/data/backup_1
    networks:
      hadoop-server:
        ipv4_address: 128.0.0.254

networks:
  hadoop-server:
    ipam:
      driver: default
      config:
        - subnet: "128.0.0.0/24"
