version: "3.9"

services:
  namenode-1:
    build:
      context: ./namenode_1
      dockerfile: dockerfile
    ports:
      - "8020:8020"
      - "8021:8021"
    volumes:
      - ./namenode_1/etc:/etc/hadoop:rw
      - ./namenode_1/metadata:/metadata:rw
      - ./namenode_1/data:/data:rw
      - ./namenode_1/src:/root/src:rw
    environment:
      - "TERM=xterm-256color"
  namenode-2:
    build:
      context: ./namenode_2
      dockerfile: dockerfile
    ports:
      - "8022:8020"
      - "8023:8021"
    volumes:
      - ./namenode_2/etc:/etc/hadoop:rw
      - ./namenode_2/metadata:/metadata:rw
      - ./namenode_2/data:/data:rw
      - ./namenode_2/src:/root/src:rw
    environment:
      - "TERM=xterm-256color"

