version: "3.9"

services:
  namenode-1:
    build:
      context: ./single_namenode
      dockerfile: dockerfile
    ports:
      - "8020:8020"
      - "8021:8021"
    volumes:
      - ./single_namenode/etc:/etc/hadoop:rw
      - ./single_namenode/metadata:/metadata:rw
      - ./single_namenode/data:/data:rw
      - ./single_namenode/src:/root/src:rw
    environment:
      - "TERM=xterm-256color"

